apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../kustomize/developer
namespace: infraportal
commonLabels:
  app.kubernetes.io/instance: web
images:
- newName: 168779643184.dkr.ecr.ap-northeast-1.amazonaws.com/iida-ke
  newTag: v1.0.0
patches:
#- path: ingress.yaml
#  target:
#    group: networking.k8s.io
#    version: v1
#    kind: Ingress
#    name: ingress
- path: service.yaml
  target:
    version: v1
    kind: Service
    name: service
- path: deployment.yaml
  target:
    version: v1
    kind: Deployment
    name: deployment
