apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../kustomize/developer
namespace: infraportal
commonLabels:
  app.kubernetes.io/instance: web
patches:
#- path: ingress.yaml
#  target:
#    group: networking.k8s.io
#    version: v1
#    kind: Ingress
#    name: ingress
- path: service.yaml
  target:
    version: v1
    kind: Service
    name: service
