- op: replace
  path: /metadata/name
  value: blue-green
- op: add
  path: /spec/project
  value: sre
- op: add
  path: /spec/source/path
  value: iida-ke/sre/blue-green
- op: add
  path: /spec/destination/namespace
  value: blue-green
- op: add
  path: /spec/syncPolicy
  value:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
