apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
spec:
  destination:
    namespace: game-2048
    server: https://kubernetes.default.svc
  project: game-2048
  source:
    path: iida-ke/application/game-2048
    repoURL: https://github.com/iida-ke-gnavi/gks-manifest.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
