apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: game-2048
  namespace: argocd
spec:
  description: game-2048
  destinations:
  - namespace: game-2048
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: "*"
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/iida-ke-gnavi/argocd.git
