apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../kustomize/developer
- ingress.yaml
- crd.yaml
namespace: grafana
commonLabels:
  app.kubernetes.io/instance: grafana
images:
- newName: grafana/grafana
  newTag: 9.5.3
patches:
#- path: ingress.yaml
#  target:
#    group: networking.k8s.io
#    version: v1
#    kind: Ingress
#    name: ingress
- path: service.yaml
  target:
    version: v1
    kind: Service
    name: service
- path: deployment.yaml
  target:
    version: v1
    kind: Deployment
    name: deployment
