apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../kustomize/argocd
patches:
- path: project.yaml
  target:
    version: v1alpha1
    kind: AppProject
    name: project
  options:
    allowNameChange: true
- path: applicationset.yaml
  target:
    version: v1alpha1
    kind: ApplicationSet
    name: applicationset
  options:
    allowNameChange: true
