apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-blue-green
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-blue-green
  template:
    metadata:
      labels:
        app: rollout-blue-green
    spec:
      containers:
      - name: rollout-blue-green-sample
        image: 168779643184.dkr.ecr.ap-northeast-1.amazonaws.com/infraportal:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: rollout-blue-green-svc-active
      previewService: rollout-blue-green-svc-preview
      autoPromotionEnabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-blue-green-svc-active
spec:
  selector:
    app: rollout-blue-green
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-blue-green-svc-preview
spec:
  selector:
    app: rollout-blue-green
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
