apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
  namespace: argocd
spec:
  destinations:
  - server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: ""
    kind: ResourceQuota
  - group: ""
    kind: LimitRange
  - group: ""
    kind: NetworkPolicy
  - group: ""
    kind: PersistentVolumeClaim
  - group: rbac.authorization.k8s.io
    kind: '*'
  - group: ""
    kind: DaemonSet
  - group: ""
    kind: HorizontalPodAutoscaler
  sourceRepos:
  - https://github.com/iida-ke-gnavi/gks-manifest.git
