apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - type: Container
    max:
      cpu: 4000m
      memory: 4000Mi
    min:
      cpu: 10m
      memory: 128Mi
    default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 10m
      memory: 128Mi
  - type: Pod
    max:
      cpu: 16000m
      memory: 4000Mi
    min:
      cpu: 10m
      memory: 128Mi
