- op: replace
  path: /metadata/name
  value: infraportal
- op: add
  path: /spec/template/spec/destination/namespace
  value: infraportal
- op: replace
  path: /spec/template/metadata/annotations
  value:
    argocd-image-updater.argoproj.io/image-list: iida-ke=168779643184.dkr.ecr.ap-northeast-1.amazonaws.com/iida-ke
    argocd-image-updater.argoproj.io/iida-ke.allow-tags: 'regexp:^test*'
    argocd-image-updater.argoproj.io/iida-ke.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: deployment.yaml
- op: add
  path: /spec/generators
  value:
    - list:
        elements:
        - name: sre-infraportal
          project: sre
          path: iida-ke/sre/infraportal
        - name: infraportal
          project: infraportal
          path: iida-ke/developer/infraportal
