apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../kustomize/argocd/application
patches:
- path: application.yaml
  target:
    version: v1alpha1
    kind: Application
    name: application
