apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../kustomize/sre
namespace: infraporetal
nameprefix: infraportal-
patches:
- path: limitrange.yaml
  target:
    version: v1
    kind: LimitRange
    name: limits
- path: resourcequota.yaml
  target:
    version: v1
    kind: ResourceQuota
    name: quota
- path: networkpolicy.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
    name: deny-metadata-access
