apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../kustomize/developer
namespace: game-2048
commonLabels:
  app.kubernetes.io/instance: web
images:
- newName: public.ecr.aws/l6m2t8p7/docker-2048
  newTag: latest
patches:
- path: service.yaml
  target:
    version: v1
    kind: Service
    name: service
- path: deployment.yaml
  target:
    version: v1
    kind: Deployment
    name: deployment
